Serveur/ProjetValise/grails-app/domain/projetvalise/User.groovy
package projetvalise

class User {
	static constraints = {
		login(blank:false, nullable:false, unique:true)
		password(blank:false, password:true)
		dateCreated()
		role(blank: false, inList:["admin", "user"])
	}

	String login
	String password
	Date dateCreated
	String role = "user"
	static hasMany = [collections: Collection];

	String toString(){
		login
	}

	boolean isAdmin(){
		return role == "admin"
	}

	def beforeInsert = {
		password = password.encodeAsSHA()
	}
}

Serveur/ProjetValise/grails-app/controllers/projetvalise/domain/CollectionController.groovy
package projetvalise.domain

import projetvalise.Collection

class CollectionController {

	def scaffold = Collection

}

Serveur/ProjetValise/grails-app/controllers/projetvalise/domain/UserController.groovy
package projetvalise.domain

import projetvalise.User

class UserController {
	def scaffold = User

	def login = {}

	def authenticate = {
		def user = User.findByLoginAndPassword(params.login, params.password.encodeAsSHA())
		if(user){
			session.user = user
			flash.message = "Hello ${user.login}!"
			redirect(url: "/")
		}else{
			flash.message = "Sorry, ${params.login}. Please try again."
			redirect(action:"login")
		}
	}

	def logout = {
		flash.message = "Goodbye ${session.user.login}"
		session.user = null
		redirect(url: "/")
	}

	/*def beforeInterceptor = [action:this.&auth,
			except:['login', 'logout', 'authenticate']]*/
	def auth() {
		if(!session.user) {
			redirect(controller:"user", action:"login")
			return false
		}
	}
}

Serveur/ProjetValise/grails-app/views/user/_form.gsp
<%@ page import="projetvalise.User" %>



<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'login', 'error')} required">
    <label for="login">
        <g:message code="user.login.label" default="Login"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="login" required="" value="${userInstance?.login}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'password', 'error')} required">
    <label for="password">
        <g:message code="user.password.label" default="Password"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field type="password" name="password" required="" value="${userInstance?.password}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'role', 'error')} required">
    <label for="role">
        <g:message code="user.role.label" default="Role"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select name="role" from="${userInstance.constraints.role.inList}" required="" value="${userInstance?.role}"
              valueMessagePrefix="user.role"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'collections', 'error')} ">
    <label for="collections">
        <g:message code="user.collections.label" default="Collections"/>

    </label>

    <ul class="one-to-many">
        <g:each in="${userInstance?.collections ?}" var="c">
            <li><g:link controller="collection" action="show" id="${c.id}">${c?.encodeAsHTML()}</g:link></li>
        </g:each>
        <li class="add">
            <g:link controller="collection" action="create"
                    params="['user.id': userInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'collection.label', default: 'Collection')])}</g:link>
        </li>
    </ul>

</div>

Serveur/ProjetValise/grails-app/views/user/create.gsp
<%@ page import="projetvalise.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                             default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-user" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${userInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${userInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form action="save">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/user/edit.gsp
<%@ page import="projetvalise.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-user" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${userInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${userInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form method="post">
        <g:hiddenField name="id" value="${userInstance?.id}"/>
        <g:hiddenField name="version" value="${userInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate=""
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/user/list.gsp
<%@ page import="projetvalise.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-user" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="login" title="${message(code: 'user.login.label', default: 'Login')}"/>

            <g:sortableColumn property="password" title="${message(code: 'user.password.label', default: 'Password')}"/>

            <g:sortableColumn property="dateCreated"
                              title="${message(code: 'user.dateCreated.label', default: 'Date Created')}"/>

            <g:sortableColumn property="role" title="${message(code: 'user.role.label', default: 'Role')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${userInstanceList}" status="i" var="userInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${userInstance.id}">${fieldValue(bean: userInstance, field: "login")}</g:link></td>

                <td>${fieldValue(bean: userInstance, field: "password")}</td>

                <td><g:formatDate date="${userInstance.dateCreated}"/></td>

                <td>${fieldValue(bean: userInstance, field: "role")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${userInstanceTotal}"/>
    </div>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/user/login.gsp
<%@ page import="projetvalise.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Welcome to Grails</title>
    <style type="text/css" media="screen">
    #status {
        background-color: #eee;
        border: .2em solid #fff;
        margin: 2em 2em 1em;
        padding: 1em;
        width: 12em;
        float: left;
        -moz-box-shadow: 0px 0px 1.25em #ccc;
        -webkit-box-shadow: 0px 0px 1.25em #ccc;
        box-shadow: 0px 0px 1.25em #ccc;
        -moz-border-radius: 0.6em;
        -webkit-border-radius: 0.6em;
        border-radius: 0.6em;
    }

    .ie6 #status {
        display: inline; /* float double margin fix http://www.positioniseverything.net/explorer/doubled-margin.html */
    }

    #status ul {
        font-size: 0.9em;
        list-style-type: none;
        margin-bottom: 0.6em;
        padding: 0;
    }

    #status li {
        line-height: 1.3;
    }

    #status h1 {
        text-transform: uppercase;
        font-size: 1.1em;
        margin: 0 0 0.3em;
    }

    #page-body {
        margin: 2em 1em 1.25em 18em;
    }

    h2 {
        margin-top: 1em;
        margin-bottom: 0.3em;
        font-size: 1em;
    }

    p {
        line-height: 1.5;
        margin: 0.25em 0;
    }

    #controller-list ul {
        list-style-position: inside;
    }

    #controller-list li {
        line-height: 1.3;
        list-style-position: inside;
        margin: 0.25em 0;
    }

    @media screen and (max-width: 480px) {
        #status {
            display: none;
        }

        #page-body {
            margin: 0 1em 1em;
        }

        #page-body h1 {
            margin-top: 0;
        }
    }
    #loginTable {
        border: none;
        margin: 30px 0px 30px 0px;
    }
    td label {
        text-align: right;
        width: 100%;
    }
    </style>
</head>
<body>
<div id="pageLogin" class="content" role="main">
    <h1>Login</h1>
    <g:if test="${flash.message}">
        <div class="message">${flash.message}</div>
    </g:if>
    <g:form action="authenticate" method="post" >
        <div class="dialog">
            <table id="loginTable">
                <tbody>
                <tr class="prop">
                    <td class="name">
                        <label for="login">Login:</label>
                    </td>
                    <td>
                        <input type="text" id="login" name="login"/>
                    </td>
                </tr>

                <tr class="prop">
                    <td class="name">
                        <label for="password">Password:</label>
                    </td>
                    <td>
                        <input type="password" id="password" name="password"/>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="buttons">
            <span class="button">
                <input class="save" type="submit" value="Login" />
            </span>
        </div>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/user/show.gsp
<%@ page import="projetvalise.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-user" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list user">

        <g:if test="${userInstance?.login}">
            <li class="fieldcontain">
                <span id="login-label" class="property-label"><g:message code="user.login.label"
                                                                         default="Login"/></span>

                <span class="property-value" aria-labelledby="login-label"><g:fieldValue bean="${userInstance}"
                                                                                         field="login"/></span>

            </li>
        </g:if>

        <g:if test="${userInstance?.password}">
            <li class="fieldcontain">
                <span id="password-label" class="property-label"><g:message code="user.password.label"
                                                                            default="Password"/></span>

                <span class="property-value" aria-labelledby="password-label"><g:fieldValue bean="${userInstance}"
                                                                                            field="password"/></span>

            </li>
        </g:if>

        <g:if test="${userInstance?.dateCreated}">
            <li class="fieldcontain">
                <span id="dateCreated-label" class="property-label"><g:message code="user.dateCreated.label"
                                                                               default="Date Created"/></span>

                <span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate
                        date="${userInstance?.dateCreated}"/></span>

            </li>
        </g:if>

        <g:if test="${userInstance?.role}">
            <li class="fieldcontain">
                <span id="role-label" class="property-label"><g:message code="user.role.label" default="Role"/></span>

                <span class="property-value" aria-labelledby="role-label"><g:fieldValue bean="${userInstance}"
                                                                                        field="role"/></span>

            </li>
        </g:if>

        <g:if test="${userInstance?.collections}">
            <li class="fieldcontain">
                <span id="collections-label" class="property-label"><g:message code="user.collections.label"
                                                                               default="Collections"/></span>

                <g:each in="${userInstance.collections}" var="c">
                    <span class="property-value" aria-labelledby="collections-label"><g:link controller="collection"
                                                                                             action="show"
                                                                                             id="${c.id}">${c?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

    </ol>
    <g:form>
        <fieldset class="buttons">
            <g:hiddenField name="id" value="${userInstance?.id}"/>
            <g:link class="edit" action="edit" id="${userInstance?.id}"><g:message code="default.button.edit.label"
                                                                                   default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>