Serveur/ProjetValise/grails-app/domain/projetvalise/Tag.groovy
package projetvalise

class Tag {
	enum TagType {
		NFC, QR, SNS
	}
	String tag
	TagType type
	Date dateCreated
	Content content
    Collection collection
	static hasMany = [logTags: LogTag];

    static constraints = {
		tag(nullable: false, blank: false, unique: true)
		dateCreated()
		content( nullable: true )
		type(nullable: false)
        collection(nullable: true)
    }
}

Serveur/ProjetValise/grails-app/controllers/projetvalise/domain/LogTagController.groovy
package projetvalise.domain

import projetvalise.LogTag

class LogTagController {

	def scaffold = LogTag

}

Serveur/ProjetValise/grails-app/controllers/projetvalise/domain/TagController.groovy
package projetvalise.domain

import projetvalise.Tag

class TagController {

	def scaffold = Tag

}

Serveur/ProjetValise/grails-app/views/tag/_form.gsp
<%@ page import="projetvalise.Tag" %>



<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'tag', 'error')} required">
	<label for="tag">
		<g:message code="tag.tag.label" default="Tag" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="tag" required="" value="${tagInstance?.tag}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'content', 'error')} ">
	<label for="content">
		<g:message code="tag.content.label" default="Content" />
		
	</label>
	<g:select id="content" name="content.id" from="${projetvalise.Content.list()}" optionKey="id" value="${tagInstance?.content?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'type', 'error')} required">
	<label for="type">
		<g:message code="tag.type.label" default="Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="type" from="${projetvalise.Tag$TagType?.values()}" keys="${projetvalise.Tag$TagType.values()*.name()}" required="" value="${tagInstance?.type?.name()}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'collection', 'error')} ">
    <label for="collection">
        <g:message code="tag.collection.label" default="Collection" />

    </label>
    <g:select id="collection" name="collection.id" from="${projetvalise.Collection.list()}" optionKey="id" value="${tagInstance?.collection?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'logTags', 'error')} ">
	<label for="logTags">
		<g:message code="tag.logTags.label" default="Log Tags" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${tagInstance?.logTags?}" var="l">
    <li><g:link controller="logTag" action="show" id="${l.id}">${l?.encodeAsHTML()}</g:link></li>
</g:each>
</ul>

</div>

Serveur/ProjetValise/grails-app/views/tag/create.gsp
<%@ page import="projetvalise.Tag" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                            default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-tag" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${tagInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${tagInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form action="save">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/tag/edit.gsp
<%@ page import="projetvalise.Tag" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                          default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-tag" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${tagInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${tagInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form method="post">
        <g:hiddenField name="id" value="${tagInstance?.id}"/>
        <g:hiddenField name="version" value="${tagInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate=""
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/tag/list.gsp
<%@ page import="projetvalise.Tag" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                          default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-tag" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="tag" title="${message(code: 'tag.tag.label', default: 'Tag')}"/>

            <g:sortableColumn property="dateCreated"
                              title="${message(code: 'tag.dateCreated.label', default: 'Date Created')}"/>

            <th><g:message code="tag.content.label" default="Content"/></th>

            <g:sortableColumn property="type" title="${message(code: 'tag.type.label', default: 'Type')}"/>

            <g:sortableColumn property="collection" title="${message(code: 'tag.collection.label', default: 'Collection')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${tagInstanceList}" status="i" var="tagInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${tagInstance.id}">${fieldValue(bean: tagInstance, field: "tag")}</g:link></td>

                <td><g:formatDate date="${tagInstance.dateCreated}"/></td>

                <td>${fieldValue(bean: tagInstance, field: "content")}</td>

                <td>${fieldValue(bean: tagInstance, field: "type")}</td>

                <td>${fieldValue(bean: tagInstance, field: "collection")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${tagInstanceTotal}"/>
    </div>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/tag/show.gsp
<%@ page import="projetvalise.Tag" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                          default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-tag" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list tag">

        <g:if test="${tagInstance?.tag}">
            <li class="fieldcontain">
                <span id="tag-label" class="property-label"><g:message code="tag.tag.label" default="Tag"/></span>

                <span class="property-value" aria-labelledby="tag-label"><g:fieldValue bean="${tagInstance}"
                                                                                       field="tag"/></span>

            </li>
        </g:if>

        <g:if test="${tagInstance?.dateCreated}">
            <li class="fieldcontain">
                <span id="dateCreated-label" class="property-label"><g:message code="tag.dateCreated.label"
                                                                               default="Date Created"/></span>

                <span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate
                        date="${tagInstance?.dateCreated}"/></span>

            </li>
        </g:if>

        <g:if test="${tagInstance?.content}">
            <li class="fieldcontain">
                <span id="content-label" class="property-label"><g:message code="tag.content.label"
                                                                           default="Content"/></span>

                <span class="property-value" aria-labelledby="content-label"><g:link controller="content" action="show"
                                                                                     id="${tagInstance?.content?.id}">${tagInstance?.content?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${tagInstance?.type}">
            <li class="fieldcontain">
                <span id="type-label" class="property-label"><g:message code="tag.type.label" default="Type"/></span>

                <span class="property-value" aria-labelledby="type-label"><g:fieldValue bean="${tagInstance}"
                                                                                        field="type"/></span>

            </li>
        </g:if>

        <g:if test="${tagInstance?.logTags}">
            <li class="fieldcontain">
                <span id="logTags-label" class="property-label"><g:message code="tag.logTags.label"
                                                                           default="Log Tags"/></span>

                <g:each in="${tagInstance.logTags}" var="l">
                    <span class="property-value" aria-labelledby="logTags-label"><g:link controller="logTag"
                                                                                         action="show"
                                                                                         id="${l.id}">${l?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

    </ol>
    <g:form>
        <fieldset class="buttons">
            <g:hiddenField name="id" value="${tagInstance?.id}"/>
            <g:link class="edit" action="edit" id="${tagInstance?.id}"><g:message code="default.button.edit.label"
                                                                                  default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>