Serveur/ProjetValise/grails-app/domain/projetvalise/Collection.groovy
package projetvalise

class Collection {
	User owner
	Double latitude
	Double longitude
	static hasMany = [tags: Tag]
	static mappedBy = [collection: Collection]
	static constraints = {
		owner(nullable: false)
		latitude(min: -90d, max: 90d)
		longitude(min: -180d, max: 180d)
	}
}

Serveur/ProjetValise/grails-app/controllers/projetvalise/domain/CollectionController.groovy
package projetvalise.domain

import projetvalise.Collection

class CollectionController {

	def scaffold = Collection

}

Serveur/ProjetValise/grails-app/controllers/projetvalise/domain/TagController.groovy
package projetvalise.domain

import projetvalise.Tag

class TagController {

	def scaffold = Tag

}

Serveur/ProjetValise/grails-app/views/collection/_form.gsp
<%@ page import="projetvalise.Collection" %>



<div class="fieldcontain ${hasErrors(bean: collectionInstance, field: 'owner', 'error')} required">
	<label for="owner">
		<g:message code="collection.owner.label" default="Owner" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="owner" name="owner.id" from="${projetvalise.User.list()}" optionKey="id" required="" value="${collectionInstance?.owner?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: collectionInstance, field: 'latitude', 'error')} required">
	<label for="latitude">
		<g:message code="collection.latitude.label" default="Latitude" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="latitude" value="${collectionInstance.latitude}" required="" type="any"/>
</div>

<div class="fieldcontain ${hasErrors(bean: collectionInstance, field: 'longitude', 'error')} required">
	<label for="longitude">
		<g:message code="collection.longitude.label" default="Longitude" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="longitude" value="${collectionInstance.longitude}" required="" type="any"/>
</div>

<div class="fieldcontain ${hasErrors(bean: collectionInstance, field: 'tags', 'error')} ">
	<label for="tags">
		<g:message code="collection.tags.label" default="Tags" />
		
	</label>
	<g:select name="tags" from="${projetvalise.Tag.list()}" multiple="multiple" optionKey="id" size="5" value="${collectionInstance?.tags*.id}" class="many-to-many"/>
</div>

Serveur/ProjetValise/grails-app/views/collection/create.gsp
<%@ page import="projetvalise.Collection" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'collection.label', default: 'Collection')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-collection" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                   default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-collection" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${collectionInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${collectionInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form action="save">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/collection/edit.gsp
<%@ page import="projetvalise.Collection" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'collection.label', default: 'Collection')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-collection" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                 default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-collection" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${collectionInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${collectionInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form method="post">
        <g:hiddenField name="id" value="${collectionInstance?.id}"/>
        <g:hiddenField name="version" value="${collectionInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate=""
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/collection/list.gsp
<%@ page import="projetvalise.Collection" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'collection.label', default: 'Collection')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-collection" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-collection" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<th><g:message code="collection.owner.label" default="Owner" /></th>
					
						<g:sortableColumn property="latitude" title="${message(code: 'collection.latitude.label', default: 'Latitude')}" />
					
						<g:sortableColumn property="longitude" title="${message(code: 'collection.longitude.label', default: 'Longitude')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${collectionInstanceList}" status="i" var="collectionInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${collectionInstance.id}">${fieldValue(bean: collectionInstance, field: "owner")}</g:link></td>
					
						<td>${collectionInstance.latitude}</td>
					
						<td>${collectionInstance.longitude}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${collectionInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

Serveur/ProjetValise/grails-app/views/collection/show.gsp
<%@ page import="projetvalise.Collection" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'collection.label', default: 'Collection')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-collection" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-collection" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list collection">
			
				<g:if test="${collectionInstance?.owner}">
				<li class="fieldcontain">
					<span id="owner-label" class="property-label"><g:message code="collection.owner.label" default="Owner" /></span>
					
						<span class="property-value" aria-labelledby="owner-label"><g:link controller="user" action="show" id="${collectionInstance?.owner?.id}">${collectionInstance?.owner?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${collectionInstance?.latitude}">
				<li class="fieldcontain">
					<span id="latitude-label" class="property-label"><g:message code="collection.latitude.label" default="Latitude" /></span>
					
						<span class="property-value" aria-labelledby="latitude-label">${collectionInstance.latitude}</span>
					
				</li>
				</g:if>
			
				<g:if test="${collectionInstance?.longitude}">
				<li class="fieldcontain">
					<span id="longitude-label" class="property-label"><g:message code="collection.longitude.label" default="Longitude" /></span>
					
						<span class="property-value" aria-labelledby="longitude-label">${collectionInstance.longitude}</span>
					
				</li>
				</g:if>
			
				<g:if test="${collectionInstance?.tags}">
				<li class="fieldcontain">
					<span id="tags-label" class="property-label"><g:message code="collection.tags.label" default="Tags" /></span>
					
						<g:each in="${collectionInstance.tags}" var="t">
						<span class="property-value" aria-labelledby="tags-label"><g:link controller="tag" action="show" id="${t.id}">${t?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${collectionInstance?.id}" />
					<g:link class="edit" action="edit" id="${collectionInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>