Serveur/ProjetValise/grails-app/domain/projetvalise/LogTag.groovy
package projetvalise
import projetvalise.Tag.TagType
class LogTag {

	Date dateCreated
	Double latitude
	Double longitude
	Tag tag
	TagType typeTag
	static constraints = {
		dateCreated()
		tag(nullable: false)
		typeTag(blank: false)
		latitude(min: -90d, max: 90d)
		longitude(min: -180d, max: 180d)
	}
}

Serveur/ProjetValise/grails-app/controllers/projetvalise/domain/LogTagController.groovy
package projetvalise.domain

import projetvalise.LogTag

class LogTagController {

	def scaffold = LogTag

}

Serveur/ProjetValise/grails-app/views/logTag/_form.gsp
<%@ page import="projetvalise.LogTag" %>



<div class="fieldcontain ${hasErrors(bean: logTagInstance, field: 'tag', 'error')} required">
	<label for="tag">
		<g:message code="logTag.tag.label" default="Tag" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="tag" name="tag.id" from="${projetvalise.Tag.list()}" optionKey="id" required="" value="${logTagInstance?.tag?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: logTagInstance, field: 'typeTag', 'error')} required">
	<label for="typeTag">
		<g:message code="logTag.typeTag.label" default="Type Tag" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="typeTag" from="${projetvalise.Tag$TagType?.values()}" keys="${projetvalise.Tag$TagType.values()*.name()}" required="" value="${logTagInstance?.typeTag?.name()}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: logTagInstance, field: 'latitude', 'error')} required">
	<label for="latitude">
		<g:message code="logTag.latitude.label" default="Latitude" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="latitude" value="${logTagInstance.latitude}" required="" type="any"/>
</div>

<div class="fieldcontain ${hasErrors(bean: logTagInstance, field: 'longitude', 'error')} required">
	<label for="longitude">
		<g:message code="logTag.longitude.label" default="Longitude" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="longitude" value="${logTagInstance.longitude}" required="" type="any"/>
</div>

Serveur/ProjetValise/grails-app/views/logTag/edit.gsp
<%@ page import="projetvalise.LogTag" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'logTag.label', default: 'LogTag')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-logTag" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                             default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-logTag" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${logTagInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${logTagInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form method="post">
        <g:hiddenField name="id" value="${logTagInstance?.id}"/>
        <g:hiddenField name="version" value="${logTagInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate=""
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

Serveur/ProjetValise/grails-app/views/logTag/list.gsp
<%@ page import="projetvalise.LogTag" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'logTag.label', default: 'LogTag')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-logTag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="list-logTag" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'logTag.dateCreated.label', default: 'Date Created')}" />
					
						<th><g:message code="logTag.tag.label" default="Tag" /></th>
					
						<g:sortableColumn property="typeTag" title="${message(code: 'logTag.typeTag.label', default: 'Type Tag')}" />
					
						<g:sortableColumn property="latitude" title="${message(code: 'logTag.latitude.label', default: 'Latitude')}" />
					
						<g:sortableColumn property="longitude" title="${message(code: 'logTag.longitude.label', default: 'Longitude')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${logTagInstanceList}" status="i" var="logTagInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${logTagInstance.id}">${fieldValue(bean: logTagInstance, field: "dateCreated")}</g:link></td>
					
						<td>${fieldValue(bean: logTagInstance, field: "tag")}</td>
					
						<td>${fieldValue(bean: logTagInstance, field: "typeTag")}</td>
					
						<td>${logTagInstance.latitude}</td>
					
						<td>${logTagInstance.longitude}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${logTagInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

Serveur/ProjetValise/grails-app/views/logTag/show.gsp
<%@ page import="projetvalise.LogTag" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'logTag.label', default: 'LogTag')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-logTag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-logTag" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list logTag">
			
				<g:if test="${logTagInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="logTag.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${logTagInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${logTagInstance?.tag}">
				<li class="fieldcontain">
					<span id="tag-label" class="property-label"><g:message code="logTag.tag.label" default="Tag" /></span>
					
						<span class="property-value" aria-labelledby="tag-label"><g:link controller="tag" action="show" id="${logTagInstance?.tag?.id}">${logTagInstance?.tag?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${logTagInstance?.typeTag}">
				<li class="fieldcontain">
					<span id="typeTag-label" class="property-label"><g:message code="logTag.typeTag.label" default="Type Tag" /></span>
					
						<span class="property-value" aria-labelledby="typeTag-label"><g:fieldValue bean="${logTagInstance}" field="typeTag"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${logTagInstance?.latitude}">
				<li class="fieldcontain">
					<span id="latitude-label" class="property-label"><g:message code="logTag.latitude.label" default="Latitude" /></span>
					
						<span class="property-value" aria-labelledby="latitude-label">${logTagInstance.latitude}</span>
					
				</li>
				</g:if>
			
				<g:if test="${logTagInstance?.longitude}">
				<li class="fieldcontain">
					<span id="longitude-label" class="property-label"><g:message code="logTag.longitude.label" default="Longitude" /></span>
					
						<span class="property-value" aria-labelledby="longitude-label">${logTagInstance.longitude}</span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${logTagInstance?.id}" />
					<g:link class="edit" action="edit" id="${logTagInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>